spring:
  application:
    name: media-base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/media_base
    username: root
    password: MySQLroot
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.media_base.pojo
  configuration:
    map-underscore-to-camel-case: true
#jwt:
#  secret=dev-secret-key: dev-secret